/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as WeeklyRouteImport } from './routes/weekly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/monthly': typeof MonthlyRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/monthly': typeof MonthlyRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/monthly': typeof MonthlyRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daily' | '/home' | '/insights' | '/monthly' | '/weekly'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daily' | '/home' | '/insights' | '/monthly' | '/weekly'
  id:
    '__root__' | '/' | '/daily' | '/home' | '/insights' | '/monthly' | '/weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRoute
  MonthlyRoute: typeof MonthlyRoute
  WeeklyRoute: typeof WeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRoute,
  MonthlyRoute: MonthlyRoute,
  WeeklyRoute: WeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
